# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Usamos el puerto 8082 para evitar conflictos con user-service (8080) y notificaciones (8081)
server.port=8086
spring.application.name=auth-service

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (H2 - En Memoria)
# ===============================
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN JWT (Seguridad)
# ===============================
# Esta es la firma digital para crear y validar los tokens (debe coincidir con la del security-service)
jwt.secret=12345

# ===============================
# LOGS Y TRAZABILIDAD (Rúbrica IE 2.3.2)
# ===============================
logging.level.com.proyecto.authservice=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# CONFIGURACIÓN EUREKA (y Feign Client)
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true