# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8086
spring.application.name=auth-service

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL - XAMPP)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3307/db_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN JWT (Seguridad)
# ===============================
# Esta es la firma digital para crear y validar los tokens
jwt.secret=

# ===============================
# LOGS Y TRAZABILIDAD (Rúbrica IE 2.3.2)
# ===============================
# Corregido el paquete para que coincida con tu estructura (com.auth_service)
logging.level.com.auth_service=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# CONFIGURACIÓN EUREKA (y Feign Client)
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true