wrapperVersion=3.3.4
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
distributionSha256Sum=2bd267ac5be7e88be236e09b7231c2c2b07300539afec1f604820efdacd4d6e9
