spring.application.name=ms-catalogo
server.port= 8082

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (H2 - En Memoria)
# ===============================
spring.datasource.url=jdbc:h2:mem:catalogodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGS Y TRAZABILIDAD
# ===============================
logging.level.com.ms_catalogo=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# CONFIGURACIÓN EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true