server:
  port: 8088

spring:
  application:
    name: ms-envios
  datasource:
    url: jdbc:mysql://localhost:3307/bd_ms_envios?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.ms_envios: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
