server:
  port: 8089

spring:
  application:
    name: ms-pedidos

  datasource:
    url: jdbc:mysql://localhost:3307/db_pedidos?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ms-carrito:
  url: http://localhost:8083/api/carrito
ms-stock:
  url: http://localhost:8081/api/stock
ms-pagos:
  url: http://localhost:8085/api/pagos
ms-envios:
  url: http://localhost:8087/api/envios
ms-notificaciones:
  url: http://localhost:8090/api/notificacion
