spring.application.name=ms-notificaciones
server port=

# ===============================
# LOGS Y TRAZABILIDAD (Rúbrica IE 2.3.2)
# ===============================
# Nivel INFO para ver el flujo de procesamiento de eventos y errores
logging.level.com.ms_notificaciones=INFO
# Para rastrear los errores capturados por el GlobalExceptionHandler
logging.level.org.springframework.web=DEBUG

# ===============================
# CONFIGURACIÓN EUREKA 
# ===============================
# Si estás usando el proyecto 'eureka-server' que se ve en tu carpeta
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true